name: Rust

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install fuse dev packages
      run: sudo apt-get install -y libfuse-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features gitcache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Execute clippy
      run: cargo clippy --all-features -- -D warnings
